### PR TITLE
test: add `external` test

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@TrySound Why was this PR closed ? 🙃

**Comment by TrySound** [comment]
@michael-ciniawsky I realised there are no global variables in worker.

**Comment by michael-ciniawsky** [comment]
kk, so `webpack.config.externals` won't work within workers aswell?

**Comment by TrySound** [comment]
@michael-ciniawsky Yep.

**Comment by michael-ciniawsky** [comment]
Thx

**Comment by symbyte** [comment]
I feel like there is a use case for this beyond using globals in a worker. I have one (the one I mentioned in #95) where I'm wanting `require` statements for certain modules to be ignored by webpack so that they can be required in the webworker directly (which can be done now due to electron introducing node integration for web workers).

**Comment by michael-ciniawsky** [comment]
@symbyte #70 ?

**Comment by symbyte** [comment]
Not exactly, In my situation there are some modules that are not being included in any of our webpack bundles (native deps that are compiled per platform like `sqlite3`). We are loading them through electron's provided `require`.

**Comment by TrySound** [comment]
Well, that's a use case

**Pull request closed without merging**
