### PR TITLE
feat: add support for `SharedWorker` && `ServiceWorker`

### LINKED ISSUE #2: [Feature] support `SharedWorker`

### LINKED ISSUE #11: [Feature] support `ServiceWorker`
Yes, I know, they are different things. **But**...
- ... [serviceworker-loader](https://github.com/markdalgleish/serviceworker-loader), is dead
- ... and it is basically a copy of an old version of this, with minor adjustments
- ... because most of the webpack code is the same for a service worker (emit a new file, allow instanciation), only the instanciation helper is different
- ... and they don't share the "worker" part of their name for no reason :)

### PR DESCRIPTION
**Pull request by boogerlad**
### Noteable Changes

Add support for `SharedWorker` && `ServiceWorker`

### Issues

- Fixes #2
- Fixes #11 
- Fixes #14 

> ℹ️  edited by @michael-ciniawsky (Formatting)

### CODE REVIEW

**Comment by jeremyblalock** [comment]
@boogerlad: do you know if anyone is actively looking at merging this? It would be very useful for me, and I'm sure others out there.

**Comment by michael-ciniawsky** [comment]
@TrySound is the current maintainer 

cc @TrySound 😛

**Comment by lili21** [comment]
any update ?

**Comment by michael-ciniawsky** [comment]
@boogerlad Could you please rebase against current master :) ?

**Comment by boogerlad** [comment]
Initial testing shows that this doesn't work yet.

**Comment by michael-ciniawsky** [comment]
The CLA Bot is complaining about commit authors aswell, either update the commit author via git or open a fresh PR please :)

**Comment by michael-ciniawsky** [comment]
Can you please rebase ? So I can finally review this :) ?

**Comment by d3viant0ne** [comment]
Feel free to reopen this if / when it gets updated

**Comment by michael-ciniawsky** [comment]
Superseded by #98, #99

**Pull request closed without merging**
