### PR TITLE
feat: support loading cross-origin workers through an inline proxy (`options.crossOrigin`)

### PR DESCRIPTION
**Pull request by ggoodman**

### CODE REVIEW

**Comment by ggoodman** [comment]
Note: I've signed the CLA.

**Comment by apexskier** [comment]
This is a feature I'm looking for as well. I'm going to pull this down and test it out.

**Comment by ggoodman** [comment]
@apexskier thanks!. As you guessed, I couldn't make anything of the PR against my branch but having merged I can now see that it LGTM.

**Comment by evilebottnawi** [comment]
@apexskier Unfortunately, we do not have enough time and energy for the current loader, maybe you want to become a champion and solve issues?

**Comment by pankajk07** [comment]
@evilebottnawi  @ggoodman  any plans if getting this merged and released ?

**Comment by evilebottnawi** [comment]
Same issue - https://github.com/webpack-contrib/worker-loader/issues/225 feel free to send a new PR

**Pull request closed without merging**
