### PR TITLE
Configurable cacheable option

### PR DESCRIPTION
**Pull request by Llorx**
Small PR. Just added an option to allow configurable cacheability, for those users that don't hit enabled-cache-bugs.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
What is use case?

**Comment by Llorx** [comment]
Use case is to avoid rebuilding the worker each time a file changes when in watch mode. By the way, just tested and I think I have one of those cache-enabled-bugs.

Just modified it now and also made a PR meanwhile.

**Comment by evilebottnawi** [comment]
Sorry it is invalid, because child compilation is never have been cached on loader level, if you want to cache it please use https://webpack.js.org/configuration/other-options/#cache

**Comment by alexander-akait** [comment]
Let's close, feel free to feedback

**Pull request closed without merging**
