### PR TITLE
refactor(loader) v2.0.0

### PR DESCRIPTION
**Pull request by d3viant0ne**
- Fixes for Webpack 4.x
- Drops support for NodeJS 4.x
- Sets minimum peerDep to Webpack 3.x

BREAKING CHANGE: Sets `engines` to `"node": ">= 6.9.0 || >= 8.9.0"`
BREAKING CHANGE: Drops support for Webpack `v2.x`

### CODE REVIEW

**Comment by ooflorent** [comment]
Some targets are no longer available in webpack 4:

- atom
- electron

**Comment by ooflorent** [comment]
I've open a PR (https://github.com/webpack/webpack/pull/6368) to expose the required internal plugins. In v2, you should drop the hot-linking of internal dependencies. This may prevent having a build step on webpack.

**Comment by switz** [comment]
Checking in on when we can merge this and #121

**Comment by benpoulson** [comment]
Really could do with this merge going ahead. Holding my team back from moving to Webpack 4.X.

**Pull request merged**
